### ISSUE TITLE
Does not work with Magento 2.4.5-p1

### ISSUE THREAD

**Issue by git-seb** [gaiterjones/magento2-module-buyxgety#2]
Plugin does not work with Magento 2.4.5-p1. Unable to add product to cart after installing plugin.

**Comment by gaiterjones** [comment]
@git-seb I know it works with 2.4.4 and PHP7. I have not tested it with 2.4.5 and the problem likely is with PHP8.

**Comment by git-seb** [comment]
Ah right okay that might be it indeed as we are on PHP 8.1 I think. Anyways no rush it was just to let you know. Currently we are using an alternative way.

**Comment by gaiterjones** [comment]
Ok, thanks, I will close this issue when I have confirmed PHP8 compatibility.

**Comment by gaiterjones** [comment]
Module is now compatible with PHP8.1 and tested with 2.4.5-p1
