### ISSUE TITLE
Free product not upgrading to next tier on adding new product

### ISSUE THREAD

**Issue by snijplank** [gaiterjones/magento2-module-buyxgety#3]
Mgento version: 2.3.7-p3
Php version: 7.4

The product does not get upgraded to the next tier product when new products get added, gives an error on adding a product tot the cart:
Cannot add product

When removing a product from the cart it gives the following error:
Notice: Undefined offset: 1 in app/code/Gaiterjones/BuyXGetY/Model/SpendXGetY.php on line 215

== That indeed solved the problem, thank you!

**Comment by snijplank** [comment]
![image](https://user-images.githubusercontent.com/22998375/206908970-643a1373-500c-41c2-a76d-2e3cf07d8a58.png)

**Comment by gaiterjones** [comment]
It looks like you do not have a description for each offer. The module requires a comma seperated list of descriptions to match each product Y. 

![image](https://user-images.githubusercontent.com/3909886/207264581-c012a026-f5cc-4baa-add0-416cbc7f713e.png)


I will update the module to check for this error.
